server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql:///QnnreSystem?useSSL=true
        username: root
        password: 1234567890
        driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    type-aliases-package: com.github.aftermathjing.questionnaire.entity